### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by pacexy** [zhw2590582/bilibili-live-recorder#5]
点开始之后时间一直显示为0，保存后文件大小也为0k

**Comment by zhw2590582** [comment]
直播间地址是多少？

**Comment by zuoyi93** [comment]
请问现在这个项目还在维护吗？我发现加入插件以后点开始时间为0，下载下来保存的文件也是0k。随便一个直播间地址，比如 https://live.bilibili.com/668

谢谢

**Comment by zhw2590582** [comment]
@zuoyi93 请使用最新的chrome浏览器，我这边测试是没问题的
